In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
import tifffile

In [2]:
filename = "datasets.hdf5"

In [3]:
#opening hdf5 file
f = h5py.File(filename, "r")

In [4]:
#initializations 
gt = []
img = []

In [5]:
#reading masks
for key in list(f['time_lapse_train']['gt']):
    data = data = np.array(f['time_lapse_train']['gt'][key])
    image_name = key.split('.')[0] + "_mask.tif"
    tifffile.imsave(image_name, data)
    gt.append(data)
    
#reading images
for key in list(f['time_lapse_train']['img']):
    data = data = np.array(f['time_lapse_train']['img'][key])
    image_name = key.split('.')[0] + "_image.tif"
    tifffile.imsave(image_name, data)
    img.append(data)

In [8]:
im1 = img[0][0]

array([[404, 387, 382, ..., 356, 338, 345],
       [396, 387, 394, ..., 350, 359, 342],
       [389, 373, 373, ..., 347, 354, 354],
       ...,
       [356, 371, 355, ..., 354, 346, 355],
       [355, 364, 366, ..., 332, 343, 367],
       [358, 365, 365, ..., 342, 362, 344]], dtype=uint16)

In [9]:
im2 = img[0][1]

array([[370, 379, 392, ..., 354, 344, 349],
       [386, 382, 380, ..., 341, 350, 354],
       [382, 377, 385, ..., 350, 352, 352],
       ...,
       [371, 365, 362, ..., 350, 357, 359],
       [351, 365, 347, ..., 347, 355, 349],
       [372, 378, 377, ..., 361, 350, 358]], dtype=uint16)

In [22]:
out = img[0][0:9]

In [18]:
print(out)

[[404 387 382 ... 354 344 349]
 [396 387 394 ... 341 350 354]
 [389 373 373 ... 350 352 352]
 ...
 [356 371 355 ... 350 357 359]
 [355 364 366 ... 347 355 349]
 [358 365 365 ... 361 350 358]]


In [19]:
np.shape(im1)

(1024, 1024)

In [20]:
np.shape(out)

(1024, 2048)